name: coral_bleaching
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip>=23.0
  - pytorch>=2.0.0
  - torchvision>=0.15.0
  - cudatoolkit=11.8
  - numpy>=1.24.4
  - scikit-learn>=1.0.0
  - tqdm>=4.60.0
  - pillow>=9.0.0
  - pyyaml>=6.0
  - matplotlib>=3.5.0
  - pip:
    - albumentations>=2.0.0
    - segmentation_models_pytorch>=0.5.0
    - peft>=0.17.0
    - accelerate>=1.10.0
    - torchmetrics>=1.8.0
    - wandb>=0.22.0
    - huggingface_hub>=0.25.0
    - transformers>=4.30.0